active_max: float64
active_mean: float64
active_min: float64
active_std: float64
bwd_bulk_bytes_mean: float64
bwd_bulk_pkt_mean: float64
bwd_bulk_rate_mean: float64
bwd_flag_psh: int64
bwd_flag_urg: int64
bwd_iat_max: float64
bwd_iat_mean: float64
bwd_iat_min: float64
bwd_iat_std: float64
bwd_iat_tot: int64
bwd_non_empty_pkt_cnt: int64
bwd_pkt_cnt: int64
bwd_pkt_hdr_len_min: int64
bwd_pkt_hdr_len_tot: int64
bwd_pkt_len_max: float64
bwd_pkt_len_mean: float64
bwd_pkt_len_min: float64
bwd_pkt_len_std: float64
bwd_pkt_len_tot: int64
bwd_pkt_per_s: float64
bwd_subflow_bytes_mean: float64
bwd_subflow_pkt_mean: float64
bwd_tcp_init_win_bytes: int64
bytes_per_s: float64
down_up_ratio: float64
dst_addr: object
dst_port: int64
flag_SYN: int64
flag_ack: int64
flag_cwr: int64
flag_ece: int64
flag_fin: int64
flag_psh: int64
flag_rst: int64
flag_urg: int64
flow_duration: int64
flow_id: object
fwd_bulk_bytes_mean: float64
fwd_bulk_pkt_mean: float64
fwd_bulk_rate_mean: float64
fwd_flag_psh: int64
fwd_flag_urg: int64
fwd_iat_max: float64
fwd_iat_mean: float64
fwd_iat_min: float64
fwd_iat_std: float64
fwd_iat_tot: int64
fwd_non_empty_pkt_cnt: int64
fwd_pkt_cnt: int64
fwd_pkt_hdr_len_min: int64
fwd_pkt_hdr_len_tot: int64
fwd_pkt_len_max: float64
fwd_pkt_len_mean: float64
fwd_pkt_len_min: float64
fwd_pkt_len_std: float64
fwd_pkt_len_tot: int64
fwd_pkt_per_s: float64
fwd_subflow_bytes_mean: float64
fwd_subflow_pkt_mean: float64
fwd_tcp_init_win_bytes: int64
iat_max: float64
iat_mean: float64
iat_min: float64
iat_std: float64
idle_max: float64
idle_mean: float64
idle_min: float64
idle_std: float64
ip_prot: int64
label: object
pkt_len_max: float64
pkt_len_mean: float64
pkt_len_min: float64
pkt_len_std: float64
pkt_len_var: float64
pkt_per_s: float64
src_addr: object
src_port: int64
timestamp: int64
